version: '3'

services:
## Router
  router01:
    image: mongo:latest
    container_name: router-01
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    ports:
      - 27117:27017
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - mongodb_cluster_router01_db:/data/db
      - mongodb_cluster_router01_config:/data/configdb
    networks:
      - mongodb_network

## Config Servers
  configsvr01:
    image: mongo:latest
    container_name: mongo-config-01 
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts 
      - mongodb_cluster_configsvr01_db:/data/db
      - mongodb_cluster_configsvr01_config:/data/configdb
    networks:
      - mongodb_network
  configsvr02:
    image: mongo:latest
    container_name: mongo-config-02 
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_configsvr02_db:/data/db
      - mongodb_cluster_configsvr02_config:/data/configdb
    networks:
      - mongodb_network
  configsvr03:
    image: mongo:latest
    container_name: mongo-config-03 
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_configsvr03_db:/data/db
      - mongodb_cluster_configsvr03_config:/data/configdb
    networks:
      - mongodb_network

## Shards
  ## Shards 01
  shard01-a:
    image: mongo:latest
    container_name: shard-01-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard01_a_db:/data/db
      - mongodb_cluster_shard01_a_config:/data/configdb
    networks:
      - mongodb_network
  shard01-b:
    image: mongo:latest
    container_name: shard-01-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard01_b_db:/data/db
      - mongodb_cluster_shard01_b_config:/data/configdb
    networks:
      - mongodb_network
  shard01-c:
    image: mongo:latest
    container_name: shard-01-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard01_c_db:/data/db
      - mongodb_cluster_shard01_c_config:/data/configdb
    networks:
      - mongodb_network

  ## Shards 02
  shard02-a:
    image: mongo:latest
    container_name: shard-02-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard02_a_db:/data/db
      - mongodb_cluster_shard02_a_config:/data/configdb
    networks:
      - mongodb_network
  shard02-b:
    image: mongo:latest
    container_name: shard-02-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard02_b_db:/data/db
      - mongodb_cluster_shard02_b_config:/data/configdb
    networks:
      - mongodb_network
  shard02-c:
    image: mongo:latest
    container_name: shard-02-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard02_c_db:/data/db
      - mongodb_cluster_shard02_c_config:/data/configdb
    networks:
      - mongodb_network

  ## Shards 03
  shard03-a:
    image: mongo:latest
    container_name: shard-03-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard03_a_db:/data/db
      - mongodb_cluster_shard03_a_config:/data/configdb
    networks:
      - mongodb_network
  shard03-b:
    image: mongo:latest
    container_name: shard-03-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard03_b_db:/data/db
      - mongodb_cluster_shard03_b_config:/data/configdb
    networks:
      - mongodb_network
  shard03-c:
    image: mongo:latest
    container_name: shard-03-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard03_c_db:/data/db
      - mongodb_cluster_shard03_c_config:/data/configdb
    networks:
      - mongodb_network

  ## Shards 04
  shard04-a:
    image: mongo:latest
    container_name: shard-04-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-04
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard04_a_db:/data/db
      - mongodb_cluster_shard04_a_config:/data/configdb
    networks:
      - mongodb_network
  shard04-b:
    image: mongo:latest
    container_name: shard-04-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-04
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard04_b_db:/data/db
      - mongodb_cluster_shard04_b_config:/data/configdb
    networks:
      - mongodb_network
  shard04-c:
    image: mongo:latest
    container_name: shard-04-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-04
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard04_c_db:/data/db
      - mongodb_cluster_shard04_c_config:/data/configdb
    networks:
      - mongodb_network

volumes:
  ## Routing
  mongodb_cluster_router01_db:
  mongodb_cluster_router01_config:

  ## Configs
  mongodb_cluster_configsvr01_db:
  mongodb_cluster_configsvr01_config:
  
  mongodb_cluster_configsvr02_db:
  mongodb_cluster_configsvr02_config:
  
  mongodb_cluster_configsvr03_db:
  mongodb_cluster_configsvr03_config:

  ## Shard 1
  mongodb_cluster_shard01_a_db:
  mongodb_cluster_shard01_a_config:
  
  mongodb_cluster_shard01_b_db:
  mongodb_cluster_shard01_b_config:
  
  mongodb_cluster_shard01_c_db:
  mongodb_cluster_shard01_c_config:

  ## Shard 2
  mongodb_cluster_shard02_a_db:
  mongodb_cluster_shard02_a_config:
  
  mongodb_cluster_shard02_b_db:
  mongodb_cluster_shard02_b_config:
  
  mongodb_cluster_shard02_c_db:
  mongodb_cluster_shard02_c_config:

  ## Shard 3
  mongodb_cluster_shard03_a_db:
  mongodb_cluster_shard03_a_config:
  
  mongodb_cluster_shard03_b_db:
  mongodb_cluster_shard03_b_config:
  
  mongodb_cluster_shard03_c_db:
  mongodb_cluster_shard03_c_config:

  ## Shard 4
  mongodb_cluster_shard04_a_db:
  mongodb_cluster_shard04_a_config:
  
  mongodb_cluster_shard04_b_db:
  mongodb_cluster_shard04_b_config:
  
  mongodb_cluster_shard04_c_db:
  mongodb_cluster_shard04_c_config:

networks:
  mongodb_network:
